an initial attempt at reducing first step of checkDistance to scaling with N in worst case (vs. N^2)
as it turns out, the logic is incorrect, and it crashes on test3 after all hydrogens and first carbon have been assigned:
  File "C:\Users\User1\MoleCoor\MolecularCoordinates.py", line 172, in checkDistance
    mappingLabels = mapping[0]
UnboundLocalError: local variable 'mapping' referenced before assignment