refactored code; in principle, it should now scale like N^2 in best case scenario
two main changes: 1. checkDistances should now scale like N rather than N^2 (except the first iteration when it will still be N^2)
2. avoided copying dictionaries per suggestion of Josh and Richard; this depends on change #1 (to iterate over atoms rather than homMap2/hetMap2; otherwise, homMap2/hetMap2 would be modified within the iterator over the elements in these dictionaries (something would be removed then readded) potentially leading to problems)
currently, many of the tests fail and test1 is slower, probably due to extra overhead (though Buckminsterfullerene is a lot faster):
test1 took 0.580 seconds ([0.5864248109745791, 0.57998369904554936, 0.58912305893626105, 0.59353227854378066, 0.59822226009171509])
test2 took 0.152 seconds ([0.15870243285110242, 0.15753762000477689, 0.15157324464422128, 0.15579487057712615, 0.15390636240080813])
test3 took 0.286 seconds ([0.292821922898022, 0.29494656443765876, 0.29416999925968224, 0.28625879825508527, 0.29494684380277381])
test4 took 2.154 seconds ([2.1541323687787131])
test5 took 1.064 seconds ([1.0637137541223805, 1.0734227394822522, 1.0752533492385208, 1.0781640543700384, 1.0705213930820801])
test6 took 0.049 seconds ([0.051762374826969548, 0.048523834733185112, 0.052027003432000285])
test7 took 0.210 seconds ([0.2097488647300132, 0.21216334757629873, 0.21662809100039127])

Continuing with tests...
A test of molecules with swapped atom types ... ok
A test of Buckminsterfullerene with itself ... FAIL
A test of distance deviations, given a mapping ... ok
A test of distinct JP-10 conformations ... ok
A test of a long linear heterogeneous chain ... FAIL
A test of a long linear homogeneous chain ... FAIL
A test of mirror images ... FAIL
A simple test (using the same molecule) of the heterogeneous case ... FAIL
A simple test (using the same molecule) of the homogenous case ... FAIL

======================================================================
FAIL: A test of Buckminsterfullerene with itself
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 40, in testBuckminsterfullerene
    self.assertEqual(q, True)
AssertionError: False != True

======================================================================
FAIL: A test of a long linear heterogeneous chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 74, in testLongLinearChainHetConf
    self.assertEqual(q, True)
AssertionError: False != True

======================================================================
FAIL: A test of a long linear homogeneous chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 65, in testLongLinearChainHomConf
    self.assertEqual(q, True)
AssertionError: False != True

======================================================================
FAIL: A test of mirror images
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 32, in testMirrorImageConf
    self.assertEqual(q, True)
AssertionError: False != True

======================================================================
FAIL: A simple test (using the same molecule) of the heterogeneous case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 14, in testSimpleHetConf
    self.assertEqual(q, True)
AssertionError: False != True

======================================================================
FAIL: A simple test (using the same molecule) of the homogenous case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 23, in testSimpleHomConf
    self.assertEqual(q, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 9 tests in 2.216s

FAILED (failures=6)