fixed issue where atomMaps being returned were null
atoms were being removed from atomMap as the stack was falling back up the recursive tree, also removing them from successfulAtomMapList in the process; this has been fixed by making a copy of the atomMap
no effect on the size of the successful atom maps, however:
test1 took 0.580 seconds ([0.57989967998726133, 0.58598243631522973, 0.58278077241660586, 0.58809764928224117, 0.59064755436794325])
test2 took 0.151 seconds ([0.16069465532630467, 0.16071372199539269, 0.15590961979804696, 0.15208406375670602, 0.15146582875756565])
test3 took 0.281 seconds ([0.29468619615062774, 0.29552855181314897, 0.28127604206679901, 0.28288441687421173, 0.28865316681310027])
test4 took 2.099 seconds ([2.0989481205013494])
test5 took 1.066 seconds ([1.0657664591449478, 1.0686135388715599, 1.0700396977828195, 1.0833323089945797, 1.0685948912501448])
test6 took 0.050 seconds ([0.052080711375328548, 0.051806863721505891, 0.049688787262068601])
test7 took 0.212 seconds ([0.21174220466567739, 0.2129123952904628, 0.21205607137219928])

Continuing with tests...
A test of molecules with swapped atom types ... ok
A test of Buckminsterfullerene with itself ... FAIL
A test of distance deviations, given a mapping ... ok
A test of distinct JP-10 conformations ... ok
A test of a long linear heterogeneous chain ... FAIL
A test of a long linear homogeneous chain ... FAIL
A test of mirror images ... FAIL
A simple test (using the same molecule) of the heterogeneous case ... FAIL
A simple test (using the same molecule) of the homogenous case ... FAIL

======================================================================
FAIL: A test of Buckminsterfullerene with itself
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 41, in testBuckminsterfullerene
    self.assertEqual(len(n), 120) #A result of 120 seems reasonable (symmetry number is 60)
AssertionError: 240 != 120

======================================================================
FAIL: A test of a long linear heterogeneous chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 75, in testLongLinearChainHetConf
    self.assertEqual(len(n), 1)
AssertionError: 2 != 1

======================================================================
FAIL: A test of a long linear homogeneous chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 66, in testLongLinearChainHomConf
    self.assertEqual(len(n), 1)
AssertionError: 2 != 1

======================================================================
FAIL: A test of mirror images
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 33, in testMirrorImageConf
    self.assertEqual(len(n), 2) #I believe the correct answer is 2
AssertionError: 4 != 2

======================================================================
FAIL: A simple test (using the same molecule) of the heterogeneous case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 15, in testSimpleHetConf
    self.assertEqual(len(n), 6)
AssertionError: 12 != 6

======================================================================
FAIL: A simple test (using the same molecule) of the homogenous case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 24, in testSimpleHomConf
    self.assertEqual(len(n), 48) #I believe the answer is 48, though I am not positive off the top of my head, and it could be higher
AssertionError: 96 != 48

----------------------------------------------------------------------
Ran 9 tests in 2.184s

FAILED (failures=6)