addressed erroneous True/False match results
successfulMatchQ, as a boolean, is immutable, so if it is changed within the homMap/hetMap functions, it is not changed outside; I have changed homBlock and hetBlock to return appropriate boolean variable
now I have a bug in the atom mappings count:
test1 took 0.570 seconds ([0.56988737395395228, 0.59211156725226211, 0.60245345427980368, 0.57911284814131392, 0.57811320991913728])
test2 took 0.151 seconds ([0.15088726360473181, 0.15056543499243613, 0.15070490802601988, 0.15829483914855125, 0.15889191224024213])
test3 took 0.287 seconds ([0.29093502107111302, 0.28653536971877713, 0.29748452666470193, 0.29088676074752495, 0.2898348812488738])
test4 took 2.150 seconds ([2.1503872698904463])
test5 took 1.095 seconds ([1.1044900958082646, 1.0953457073454871, 1.1292076227565246, 1.0955631232461105, 1.0957633581921709])
test6 took 0.051 seconds ([0.051019612827888139, 0.05223918123672, 0.051482241458062461])
test7 took 0.207 seconds ([0.212924477831681, 0.20669030561146684, 0.22272209177423363])

Continuing with tests...
A test of molecules with swapped atom types ... ok
A test of Buckminsterfullerene with itself ... FAIL
A test of distance deviations, given a mapping ... ok
A test of distinct JP-10 conformations ... ok
A test of a long linear heterogeneous chain ... FAIL
A test of a long linear homogeneous chain ... FAIL
A test of mirror images ... FAIL
A simple test (using the same molecule) of the heterogeneous case ... FAIL
A simple test (using the same molecule) of the homogenous case ... FAIL

======================================================================
FAIL: A test of Buckminsterfullerene with itself
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 41, in testBuckminsterfullerene
    self.assertEqual(len(n), 120) #A result of 120 seems reasonable (symmetry number is 60)
AssertionError: 240 != 120

======================================================================
FAIL: A test of a long linear heterogeneous chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 75, in testLongLinearChainHetConf
    self.assertEqual(len(n), 1)
AssertionError: 2 != 1

======================================================================
FAIL: A test of a long linear homogeneous chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 66, in testLongLinearChainHomConf
    self.assertEqual(len(n), 1)
AssertionError: 2 != 1

======================================================================
FAIL: A test of mirror images
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 33, in testMirrorImageConf
    self.assertEqual(len(n), 2) #I believe the correct answer is 2
AssertionError: 4 != 2

======================================================================
FAIL: A simple test (using the same molecule) of the heterogeneous case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 15, in testSimpleHetConf
    self.assertEqual(len(n), 6)
AssertionError: 12 != 6

======================================================================
FAIL: A simple test (using the same molecule) of the homogenous case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\User1\MoleCoor\conftest.py", line 24, in testSimpleHomConf
    self.assertEqual(len(n), 48) #I believe the answer is 48, though I am not positive off the top of my head, and it could be higher
AssertionError: 96 != 48

----------------------------------------------------------------------
Ran 9 tests in 2.215s

FAILED (failures=6)